export const styles = {
  parentContainer:
    " bg-blue w-full h-auto max-h-full p-6 flex flex-col space-y-4 flow-hide rounded-2xl outline-none border-none ",
  headerSession: "w-full h-full flex justify-end items-center",
  header: " flex w-8/12  justify-between items-center",
  header1: " flex w-7/12  justify-between items-center",
  headerTitle: "  lg:text-[1.5rem] text-[14px]   biome-bold font-bold text-white ",
  closeIcon: "text-grey text-xl cursor-pointer",
  formContainer: "flex flex-col space-y-2  md:space-y-8 w-full h-full",
  singleField: "flex flex-col  md:space-y-4 w-full ",
  label: "m-story biome-semibold text-white md:text-xl ",
  input: "border-none outline-none text-white bg-semiBlue  w-full",
  inputContainer: "py-2 px-4 bg-semiBlue rounded-lg ",
  textArea: "border-none outline-none text-white bg-semiBlue  w-full h-24",
  btnContainer: "w-full flex justify-center items-center pb-6",
    btn: "text-white m-ctaBtn biome-semigold bg-lightBlue  py-[1rem] px-[2.4rem] mt-[1rem] md:mt-[0rem]",
  wait: "flex space-x-4 items-center ",
  waiting: "biome-regular text-white text-xl",
  validate: "text-yellow biome-regular text-[14px] md:text-xl text-center",
};